# Generated by Django 4.1.2 on 2022-11-01 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mijnportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileP',
            new_name='UserProfile',
        ),
    ]
